### ISSUE TITLE
Hacker Base Fission logo?

### ISSUE THREAD

**Issue by jbenet** [protocol/labweek-2022#391]
- i may be misremembering but I thought the hacker base was put on by Fission? if so should it be the fission logo in the event? 
- or if joint, maybe show both fission + FF? 🤷  (can do this by making 1 image w/ both logos side by side)

<img width="1974" alt="Screen Shot 2022-10-22 at 07 29 47" src="https://user-images.githubusercontent.com/138401/197324042-b6547687-b2c1-4312-979b-1f60c98a1a5c.png">

**Comment by laeccles** [comment]
@jbenet I am updating this now!
