### ISSUE TITLE
Incorrect [Register] hyperlink

### ISSUE THREAD

**Issue by HumanDAO** [protocol/labweek-2022#424]
On the [BIC website](https://breakthroughs-in-computing.labweek.io/)

The [REGISTER] button for [Convergent Research on Brain-Computer Interfaces](https://breakthroughs-in-computing.labweek.io/day/oct-27) is linking to [Oct 26th Speakers](https://breakthroughs-in-computing.labweek.io/day/oct-26) rather than lu.ma.

@jbenet @mikeal  @autonome @olizilla @BigLep

**Comment by laeccles** [comment]
Hi @HumanDAO The Join in Person button is now hyperlinked to the correct [lu.ma](https://lu.ma/brain-computer-interfaces).
