### ISSUE TITLE
Alignment of schedule grid

### ISSUE THREAD

**Issue by jbenet** [protocol/labweek-2022#43]
The schedule grid got misaligned in spacing:

- width of each column (day) should be the same
- height of each row (event) should have same min-height (might get larger), a bit larger than currently (one of the rows looks too small)

![image](https://user-images.githubusercontent.com/138401/189939052-49ca94a7-8e00-41e6-8b87-3cfe34e8bdf6.png)

**Comment by jbenet** [comment]
this may have been fixed? not sure

**Comment by tbenbow** [comment]
This has been fixed.
